### ISSUE TITLE
Optimize release builds - multiple tracking issues

### ISSUE THREAD

**Issue by yadavcbala** [opendistro-for-elasticsearch/data-prepper#145]
1. Currently, we have a similar looking distributions block in all subprojects of archives, we can move this to subprojects closure in archives build.gradle. It is little tricky as the custom distribution name depends on subproject name _[and gradle does not let using string as custom distribution name]_. 
2. Upload to S3 is uploading tars individually which lets us use individual task to upload tars but we could also consider adding a batch upload task which will generate the fileTree of all subproject tars and zips
3. Bucket policy and IAM roles - We can automate adding roles and updating bucket policies which will completely remove manual work of adding IAM policies for odfe infra s3 access.
4. Move common tasks to parent build - currently it is not immediately inherent as the task names depend on subproject name. Check if there is a way to override the name

**Comment by yadavcbala** [comment]
Moving below tasks to low priority as of now

* Upload to S3 is uploading tars individually which lets us use individual task to upload tars but we could also consider adding a batch upload task which will generate the fileTree of all subproject tars and zips
* Bucket policy and IAM roles - We can automate adding roles and updating bucket policies which will completely remove manual work of adding IAM policies for odfe infra s3 access.

**Comment by kowshikn** [comment]
@yadavcbala can you clean this issue and update the objective for next release. (I understand some have already been fixed in the previous release, lets start tracking thing more closer in the next release)

**Comment by kowshikn** [comment]
Discussed offline. These are low priority, we can create issue in Q3 2020.
