### ISSUE TITLE
Add monitoring support for Data Prepper

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#201]
Data Prepper should provide a way for users to monitor the various components that are running. We will expose a GET API endpoint which allows the user to get the current state of metrics for the running Data Prepper. 

While certain components have specific metrics that apply to them, there are also certain metrics which apply more generically to processors, sinks, and buffers. The following metrics will be provided by default to all components of that type:

- Prepper: Records in, records out, time elapsed
- Sink: Records out, time elapsed
- Buffer: Records written, records read, write time elapsed, read time elapsed, and timeouts

For implementation, we will use Micrometer.io for metrics instrumentation, and Prometheus for the metrics backend. Micrometer allows us to decouple metrics instrumentation from backend implementation, and swap metrics backends if needed. Prometheus is widely used and supported, and provides customers with many options for consumption.

**Comment by AustinTag** [comment]
Data Prepper should provide a way for users to monitor the various components that are running. We will expose a GET API endpoint which allows the user to get the current state of metrics for the running Data Prepper. 

While certain components have specific metrics that apply to them, there are also certain metrics which apply more generically to processors, sinks, sources, and buffers. The following metrics will be provided by default to all components of that type:

- Prepper: Records in, records out, time elapsed
- Sink: Records out, time elapsed
- Buffer: Records written, records read, write time elapsed, read time elapsed, and timeouts
- Source: Records out

For implementation, we will use Micrometer.io for metrics instrumentation, and Prometheus for the metrics backend. Micrometer allows us to decouple metrics instrumentation from backend implementation, and swap metrics backends if needed. Prometheus is widely used and supported, and provides customers with many options for consumption.

**Comment by kowshikn** [comment]
@chenqi0805 Can you check with Austin and close this issue if its complete.

**Comment by AustinTag** [comment]
The only thing left on this issue is to normalize naming across metrics. For example: 

span_errors_counter
bulk_request_errors

These are both error counters but have different naming patterns. This should be a quick fix and then we can close out this task.

**Comment by chenqi0805** [comment]
@AustinTag I doublechecked current master and it is all camel case now. Or do you mean we should give them the same name? AFAICT, the former is still different from the later as a bulkRequest will include multiple spans.

**Comment by AustinTag** [comment]
I see. I'm not concerned with the naming of objects in the code so much as the metric name that is exposed externally. If all of those follow the same pattern then I think we are good to close this issue.
