### ISSUE TITLE
Add Log management for Data Prepper

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#202]
This issue covers below listed sub-issues

- [x] Update default log4j.properties
- [ ] Add capability to Data Prepper to parse jvm.options file
     - [ ] Add options parser
     - [ ] Implement priority order for the options
     - [ ] Update distribution -linux, macos
     - [ ] Update docker
     - [ ] Update documentation 
     - [ ] Update default log location

Idea is to let users pass the overriding configuration options in jvm.options files and DP should parse these options and apply according to below priority order. The intention is to simplify configuring JVM and other options.

Priority Order:

```
System JVM Options < JVM options from jvm.options < jvm options from DATA_PREPPER_JAVA_OPTS
```

**Comment by yadavcbala** [comment]
Some of the items listed under this issue are now downgraded for GA

**Comment by kowshikn** [comment]
Discussed offline with @yadavcbala, we now have the log levels configuration as a part of the data-prepper configuration yaml. Closing this story by moving the objectives of updating docker, artifacts start script etc with this information in a separate story to track it.
