### ISSUE TITLE
Expose "list" and "shutdown" server APIs for DataPrepper 

### ISSUE THREAD

**Issue by AustinTag** [opendistro-for-elasticsearch/data-prepper#233]
Right now we have no way of shutting down the data prepper without actually hard-quitting the JVM process. 

- [x] /list : lists all pipelines, with state indicating whether they are running
- [x] /shutdown : stops all running pipelines gracefully, and then shuts down the data prepper instance (should leave no JVM process running)

**Comment by kowshikn** [comment]
> - /stop/{pipelinelineName} : stops the pipeline named "pipelineName"
> - /start/{pipelineName}: starts the pipeline named "pipelineName"

Shall we remove the above from the scope? The reason is we need more logic of Connected pipelines etc and I think for now start and stop will do the desired behavior.

**Comment by AustinTag** [comment]
Yep, that makes sense.

**Comment by wrijeff** [comment]
Merged #236
