### ISSUE TITLE
Evaluate dependency injection frameworks for Data Prepper

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#252]
As Data Prepper and its plugins grow, we might be able to cut down in complexity by bringing in something like Guice or Dagger. Specifically looking at:
* Removing manually created Singletons
* Allowing for complex constructors, taking in more than just a `PluginSetting` arg (e.g. Guice's AssistedInject)
* Auto-injecting metrics objects
* ???

**Comment by kowshikn** [comment]
So we want to make Data Prepper Core to be a standalone project and have plugins installed using a `Plugin Repository`. I do not think Guice/Dagger will help us. Complex Constructors will be a no as things will explode and Plugin Setting will be the only contract between plugin and core project. 

Do you think this issue is still required?

**Comment by wrijeff** [comment]
Ah, thanks for the info. One my concerns is the limitation of plugin constructors to only accept a PluginSetting argument. Without declaring any additional constructors, this means each "default" constructor will potentially be calling `new` multiple times as the Plugin is required to set up its own dependencies. This leads to a single class having more responsibilities, and makes unit testing a bit harder. Example:
```
    public PeerForwarder(final PluginSetting pluginSetting) {
        super(pluginSetting);
        this.peerClientPool = new PeerClientPool();
        this.hashRing = new HashRing();
    }
```
compared to something like
```
    public PeerForwarder(final PluginSetting pluginSetting,
                         final PeerClientPool peerClientPool,
                         final HashRing hashRing {
        super(pluginSetting);
        this.peerClientPool = peerClientPool;
        this.hashRing = hashRing;
    }
```
Currently PeerForwarder hacks around this by [chaining constructors](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/master/data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java#L33-L54). I agree DI frameworks aren't necessarily the answer, however it'd be beneficial to have a pattern or something other Plugins can follow to invert their own dependencies.

**Comment by kowshikn** [comment]
I still don't the the DI framework will help us and chaining leaves the responsibility within the plugin. Anyway I am going to close this and reference it in the Plugin Repository Story.
