### ISSUE TITLE
AWS request signing for Elasticsearch sink

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#282]
The ES sink should have the capability to sign requests when communicating with an AWS ES cluster. Update the Elasticsearch plugin to be configurable for request signing. [These AWS docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-java) appear to be a good starting point.

- [x] AWS sigv4 signing
- [ ] Identify the open distro security permissions required for Data Prepper sink plugin.
- [ ] Implement AWS SigV4 + FGAC

**Comment by kowshikn** [comment]
The changes are in v0.7.x branch. Planning to have support for IAM + FGAC domains in the next march release, keeping the issue open.
