### ISSUE TITLE
Create CloudFormation templates for simplified deployment

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#284]
**Is your feature request related to a problem? Please describe.**
Facilitate the deployment of Data Prepper instances using an infrastructure-as-code framework. 

**Describe the solution you'd like**
We can start with CloudFormation templates and expand to other frameworks in the future.

**Describe alternatives you've considered (Optional)**
Terraform, CDK, k8s files for prod, etc.

**Additional context**
We'll need to spend some time deciding on the contents of the CFN templates before implementing, feel free to post thoughts/ideas here to discuss.

**Comment by kowshikn** [comment]
@wrijeff closing this. The low-priority exists to make it better.
