### ISSUE TITLE
Update setup/deployment instructions

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#288]
**Is your feature request related to a problem? Please describe.**
We have documentation on the overall project structure and how to setup a dev environment, however we still need guidelines on how to configure and deploy a Data Prepper instance for the trace analytics usecase. 

**Describe the solution you'd like**
We'll need to provide generic setup instructions in the [existing setup readme](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/master/docs/readme/trace_setup.md).

**Additional context**
Should be generic configuration and deployment steps w/ the container. #284 is already covering deployment via CloudFormation.

**Comment by kowshikn** [comment]
We are covered for Feb Release but I think, we need to improve a lot for March release with Kuberenetes.
