### ISSUE TITLE
Feb release scaling guidlines

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#304]
- [x] Update CFN to have parameters `workers`, `buffer_size`, `batch_size`, `jvm-heap`. The `jvm-heap` is set hrough environment variable `JAVA_OPTS`.
- [x] Update the otel config. 
- [x] Scaling and tuning section that provides the users the guidelines to configure Data Prepper. Have an example `ExportTraceRequest` is the throughput. 
- Create a big AES cluster 3-4 i3.xl with 2TB. 
- Create a IAM role in the AES using this[ instructions](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/v0.7.x/data-prepper-plugins/elasticsearch/security.md)
- Launch Data Prepper using this [cfn template](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/v0.7.x/deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml) with  instance type of c4.xlarge, 100GB, buffer_size= 1024, batch_size=24, workers-8 and jvm= 1GB 
- Create an AMI with these [instructions](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/master/examples/aws/jaeger-hotrod-on-ec2/setup-jaeger-hotrod.sh) as launch script.
-  look for number of docs per second in Amazon Elasticsearch.

**Comment by chenqi0805** [comment]
AES: 7.9. 4 i3.xlarge data nodes.

DataPrepper: 
instanceType: r5.xlarge
Heap(MB): 2048
PipelineBatchSize(MB): 8
PipelineBufferSize(MB): 512
PipelineWorkerCount: 1

Docs/second. Latency(ms)
2100 - 2200.    0.2
