### ISSUE TITLE
Improve CFN script to report failures correctly

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#313]
Currently the [EC2 CloudFormation template](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/master/deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml) is simplistic in that it never reports a failure when starting Data Prepper. As we allow for more options to be configured (e.g. Java heap size), there's a risk that the application fails to start successfully. 

Update the CFN template to correctly report the status of the Data Prepper application back to CloudFormation.

**Comment by kowshikn** [comment]
Discussed offline, we will scope this issue and prioritize it. We do not plan to have more work for the next week release, but this will be goo starter for next release.

**Comment by wrijeff** [comment]
Simple "check" would be to inspect the data prepper log output for the presence of a success message
