### ISSUE TITLE
March Release Tasks

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#325]
- [x] Update Release artifacts and Docker images to support the new `data-prepper-configuration.yml` which is the way users can configure data prepper server port, tls settings and log leve settings.

- [x] Update  all Readme documentations to reflect the march release features.

**Comment by wrijeff** [comment]
* Repo: https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/docs/readme/configuration.md#server-configuration
* ODFE: https://opendistro.github.io/for-elasticsearch-docs/docs/trace/data-prepper/#configure-the-data-prepper-server
* AWS: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/trace-analytics.html#trace-dp
