### ISSUE TITLE
Timeout exception will cause Data Prepper to crash

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#443]
We should log this and retry this forever as we want to wait till the buffer is full. Throwing a runtime exception will crash the Data Prepper in the case of child pipeline is down. 

https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/PipelineConnector.java#L54-L59

**Comment by wrijeff** [comment]
Resolved by #445, closing this as it will be merged to main next week
