### ISSUE TITLE
Connected Pipelines Exit scenario

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#444]
https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/docs/readme/error_handling.md#connected-pipelines 

Our usecase is that when a child pipeline crashes the parent pipeline should crash eventually. We need to make sure that this is tested and update the handling/clean up of resources.

**Comment by kowshikn** [comment]
Discussing this with Bala now.

**Comment by yadavcbala** [comment]
At the time of this writing, When child pipeline crashes [_throws a RunTimeException for whatever reason_], the child pipeline triggers shutdown. As part of this shutdown process, the pipeline connector [which acts as the sink for parent pipeline and source for child pipeline] receives signal to stop the source. The PipelineConnector will fail all further sink actions as well which means parent pipeline's sink is failing which triggers parent pipeline's shutdown

https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/PipelineConnector.java#L61-L67
