### ISSUE TITLE
Investigate usability of Retry4j in Elasticsearch plugin.

### ISSUE THREAD

**Issue by chenqi0805** [opendistro-for-elasticsearch/data-prepper#45]
https://github.com/elennick/retry4j

**Comment by AustinTag** [comment]
You may want to look into failsafe as well. I have used it and its pretty seamless and well featured:

https://github.com/jhalterman/failsafe

**Comment by kowshikn** [comment]
The only problem though is Elasticsearch retry requires a lot more work, I couldn't think of any existing retry library that can actually support this behaviour. But its worth exploring.

**Comment by kowshikn** [comment]
I investigate this and found that  both libraries are not great to use with Elasticsearch client. Closing this.
