### ISSUE TITLE
Update CFN template to allow for username/password

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#490]
EC2/CFN template deployed Data Prepper fails to connect to AES domains with fine grained access control. 

Update the template to optionally accept username/password parameters, then if they are present configure the ES sinks to connect with user/pass instead of sigv4.

**Comment by wrijeff** [comment]
@chenqi0805 could you ensure this update reaches the 1.0.x template as well?

**Comment by chenqi0805** [comment]
Sure. Will do
