### ISSUE TITLE
Provide option to use AWS Cloud Map API as the PeerForwarder Endpoint provider.

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#730]
This option will benefit Data Preppers deployed using AWS Service Discovery provided by AWS Cloud Map.

**Comment by wrijeff** [comment]
https://docs.aws.amazon.com/cloud-map/latest/api/API_DiscoverInstances.html

**Comment by dlvenable** [comment]
This issue was completed in OpenSearch 1.1.
