### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by dlvenable** [opendistro-for-elasticsearch/data-prepper#877]
**Is your feature request related to a problem? Please describe.**

Update dependency versions with possible security vulnerabilities.

**Describe the solution you'd like**

Updating dependency versions

**Comment by laneholloway** [comment]
Please make a note of which dependences can't be upgraded (e.g. we're reliant on a X.Y and can't go to X.(Y+1) or there is no greater version).

**Comment by dlvenable** [comment]
We are unable to update the following dependencies:

* elasticsearch:build-tools:7.10.2 -> This is the last open source version. Starting in Data Prepper 1.2, we are using OpenSearch libraries instead.
* checkstyle:8.20 -> The build fails with this update. It appears to be at least partially because of the ElasticSearch build tools. Regardless, this dependency is only used a compile/build-time.
